// API 1
GET http://localhost:3000/details/e83d9ff6-9035-4318-9954-276c56599b4a/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE2ODkzNTI5MDZ9.OSowQnEPvHyzbb_TdaXHjv25ZOIpd3-ecW34rGQne3A

###

// API 2
PUT http://localhost:3000/update/e83d9ff6-9035-4318-9954-276c56599b4a/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE2ODkzNTI5MDZ9.OSowQnEPvHyzbb_TdaXHjv25ZOIpd3-ecW34rGQne3A
Content-Type: application/json

{
   "userImage": "https://tse2.mm.bing.net/th?id=OIP.2chE4xaPW_-Un3RmEIcIYwAAAA&pid=Api&P=0&h=180"
}

###

// API 3
POST http://localhost:3000/insert/
Content-Type: application/json

{
   "userName": "adam_richard",
    "userEmail": "adamrichard1985@gmail.com",
    "userPassword": "richa123",
    "userImage": "https://tse1.mm.bing.net/th?id=OIP.ZIlIk0TnjJGaTv8XttXjvgHaHa&pid=Api&P=0&h=180",
    "totalOrders": "6"
}

###

// API 4
GET http://localhost:3000/image/e83d9ff6-9035-4318-9954-276c56599b4a/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwidXNlcklkIjoyLCJpYXQiOjE2ODkzNTI5MDZ9.OSowQnEPvHyzbb_TdaXHjv25ZOIpd3-ecW34rGQne3A

###

// API 5
DELETE http://localhost:3000/delete/e83d9ff6-9035-4318-9954-276c56599b4a/
